#! /bin/sh

case $1 in
    desc )
	echo "common archive tools"
	return
	;;
    longdesc )
	echo "This module knows common archive suffixes and ways to unpack them."
	return
	;;
    init )
	;;
    version )
	echo "0.1"
	return
	;;
    * )
	return
	;;
esac

#@ archive_parse URL
#@ Output: pwiz_result:
# FIXME: is ugly, has no callback
function archive_check_extension {
    local ext
    case "$1" in
	*.tar.gz )
	    ext=.tar.gz
	    archive_seq="tar -z -x -f"
	    ;;
	*.tgz )
	    ext=.tgz
	    archive_seq="tar -z -x -f"
	    ;;
	*.tar.bz2 )
	    ext=.tar.bz2
	    archive_seq="tar -j -x -f"
	    ;;
	*.tbz2 )
	    ext=.tbz2
	    archive_seq="tar -j -x -f"
	    ;;
	* )
	    return 1
	    ;;
    esac
    pwiz_result="${1%$ext}"
}

#@ archive_mode_{suffix} URI
#function archive_parse_targz {
#    
#}
