#!/usr/bin/perl -w

# Code based on XML::Parser(3pm)

# Does not handle multi-line strings and nested elements.

use XML::Parser;

sub handle_start
{
  print "begin\n";
  $gelement = "";
}

sub handle_char
{
  my ($expat, $element) = @_;
  $gelement = $element;
  $gelement =~ s/\'/\'\\\'\'/ ;
}

sub handle_end
{
  my ($expat, $element) = @_;
  $element =~ s/-/_/ ;
  print "local xml_$element='$gelement'\n";
}

$p1 = new XML::Parser();
$p1->setHandlers(Char => \&handle_char, Start => \&handle_start, End => \&handle_end);
$p1->parsefile($ARGV[0]);
