#! /bin/sh

case $1 in
    desc )
	echo "installwatch module"
	return
	;;
    longdesc )
	echo "This module is able to collect file list information collected by installwatch during install process."
	return
	;;
    init )
	pwiz_phase_new installwatch after post
	pwiz_phase_add_callme installwatch
	;;
    installwatch )
	installwatch_raw_file=$PWIZ_TMPDIR/$pwiz_project_project/files_raw.lst
	installwatch_file=$PWIZ_TMPDIR/$pwiz_project_project/files.lst
	rm -rf $PWIZ_TMPDIR/$pwiz_project_project
	mkdir -p $PWIZ_TMPDIR/$pwiz_project_project
	for installwatch_stage in $PWIZ_TMPDIR/pwiz_run/$pwiz_project_project/* ; do
	    exec 3<$installwatch_stage
	    installwatch_IFS_save="$IFS"
	    IFS=$'\t\n'
	    while read -u3 installwatch_a1 installwatch_a2 installwatch_a3 installwatch_a4 ; do
		case "$installwatch_a2" in
		    open )
			installwatch_add "$installwatch_a3"
			;;
		    symlink | link )
			installwatch_add "$installwatch_a4"
			;;
# FIXME %dir
		    mkdir )
			installwatch_add "$installwatch_a3" dir
			;;
		esac
	    done
	    exec 3<&-
	done
	IFS="$installwatch_IFS_save"
	LANG=C sort <$installwatch_raw_file | uniq >$installwatch_file
# FIXME:
#	rm -rf $PWIZ_TMPDIR/pwiz_run/$pwiz_project_project
	return
	;;
    version )
	echo "0.1"
	return
	;;
    * )
	return
	;;
esac

# FIXME: implement no install root
function installwatch_add {
    case $1 in
# FIXME: not fixed list
	/tmp/* | /dev/null | /dev/tty* )
	    ;;
	$PWIZ_UNPACKDIR/* | $PWIZ_BUILDDIR/* | $PWIZ_SRCDIR/* | $PWIZ_TMPDIR/* )
	    ;;
	$PWIZ_INSTALLROOT/* )
	    if test -e "$1" ; then
# FIXME faster redirection
		echo "${1##$PWIZ_INSTALLROOT}" >>$installwatch_raw_file
	    fi
	    ;;
	* )
	    echo "ERROR: FIXME: access violation $1"
	    ;;
    esac
}
