#! /bin/sh

case $1 in
    desc )
	echo "archive unpacking"
	return
	;;
    longdesc )
	echo "This module analyzes filename and tries to unpack it."
	return
	;;
    init )
	pwiz_module_uses archive
	pwiz_phase_new unpack after setup
	pwiz_phase_add_callme_arg unpack prepare
	pwiz_phase_add_run_eval unpack '$archive_seq "$PWIZ_SRCDIR/$pwiz_project_project/${package_uri##*/}"'
	pwiz_phase_add_callme_arg unpack search_dirname
	pwiz_phase_add_run_eval unpack 'cd "$unpack_dirname"'
	return
	;;
    version )
	echo "0.1"
	return
	;;
    prepare )
# FIXME subproject, these actions are outside build project
	rm -rf "$PWIZ_UNPACKDIR/$pwiz_project_project"
	mkdir -p "$PWIZ_UNPACKDIR/$pwiz_project_project"
	mkdir -p "$PWIZ_SRCDIR/$pwiz_project_project"
# FIXME: URI / name .tar.gz can be .tar.bz2. More archives to unpack.
	cp -a "$PWIZ_TMPDIR/${package_uri##*/}" $PWIZ_SRCDIR/$pwiz_project_project
	cd $PWIZ_UNPACKDIR/$pwiz_project_project
	return
	;;
    search_dirname )
	unpack_dirname=
	for unpack_name in * ; do
	    if test -d "$unpack_name" ; then
		if test -z "$unpack_dirname" ; then
		    unpack_dirname="$unpack_name"
		else
		    pwiz_fatal "FIXME: unpacking without topdir is not yet implemented"
		fi
	    else
		pwiz_fatal "FIXME: unpacking without topdir is not yet implemented"
	    fi
	done
	return
	;;
    * )
	return
	;;
esac

