#! /bin/sh

case $1 in
    desc )
	echo "RPM database engine"
	return
	;;
    longdesc )
	echo "This engine contacts RPM database for answering package-related questions."
	return
	;;
esac

# pwiz_pkgdb_who_owns file
function pwiz_engine_pkgdb_rpm_who_owns {
    pwiz_result="$(rpm -qf "$@")"
}
